#!/usr/bin/env bash

fastlane avanti_beta
fastlane avanti_staging_beta
fastlane avanti_test_beta

fastlane continental_beta
fastlane continental_staging_beta
fastlane continental_test_beta

fastlane parkspantry_beta
fastlane parkspantry_staging_beta
fastlane parkspantry_test_beta

fastlane sodexo_beta
fastlane sodexo_staging_beta
fastlane sodexo_test_beta
